#############################################################################
# Makefile for building: Schegolkova_191_352_4sem
# Generated by qmake (3.1) (Qt 5.15.2)
# Project:  Schegolkova_191_352_4sem.pro
# Template: app
# Command: C:\Qt\5.15.2\android\bin\qmake.exe -o Makefile Schegolkova_191_352_4sem.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug" "ANDROID_ABIS=armeabi-v7a x86 x86_64"
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: all
install: armeabi-v7a-x86-x86_64-install 
uninstall: armeabi-v7a-uninstall x86-uninstall x86_64-uninstall 
QMAKE         = C:\Qt\5.15.2\android\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = C:\Qt\5.15.2\android\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = C:\Qt\5.15.2\android\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = cmd /c move
TAR           = 
COMPRESS      = 
DISTNAME      = Schegolkova_191_352_4sem1.0.0
DISTDIR = C:\Users\Vasilisa\Documents\Schegolkova_191_352_4sem\.tmp\Schegolkova_191_352_4sem1.0.0
SUBTARGETS    =  \
		armeabi-v7a \
		x86 \
		x86_64


armeabi-v7a: FORCE
	$(MAKE) -f $(MAKEFILE).Armeabi-v7a
armeabi-v7a-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Armeabi-v7a 
armeabi-v7a-all: FORCE
	$(MAKE) -f $(MAKEFILE).Armeabi-v7a all
armeabi-v7a-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Armeabi-v7a clean
armeabi-v7a-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Armeabi-v7a distclean
armeabi-v7a-install: FORCE
	$(MAKE) -f $(MAKEFILE).Armeabi-v7a install
armeabi-v7a-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Armeabi-v7a uninstall
x86: FORCE
	$(MAKE) -f $(MAKEFILE).X86
x86-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).X86 
x86-all: FORCE
	$(MAKE) -f $(MAKEFILE).X86 all
x86-clean: FORCE
	$(MAKE) -f $(MAKEFILE).X86 clean
x86-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).X86 distclean
x86-install: FORCE
	$(MAKE) -f $(MAKEFILE).X86 install
x86-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).X86 uninstall
x86_64: FORCE
	$(MAKE) -f $(MAKEFILE).X86_64
x86_64-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).X86_64 
x86_64-all: FORCE
	$(MAKE) -f $(MAKEFILE).X86_64 all
x86_64-clean: FORCE
	$(MAKE) -f $(MAKEFILE).X86_64 clean
x86_64-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).X86_64 distclean
x86_64-install: FORCE
	$(MAKE) -f $(MAKEFILE).X86_64 install
x86_64-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).X86_64 uninstall

armeabi-v7a-x86-x86_64-install: FORCE
	$(MAKE) -f $(MAKEFILE).Armeabi-v7a install
	$(MAKE) -f $(MAKEFILE).X86 install
	$(MAKE) -f $(MAKEFILE).X86_64 install

Makefile: Schegolkova_191_352_4sem.pro ..\..\..\..\Qt\5.15.2\android\mkspecs\android-clang\qmake.conf ..\..\..\..\Qt\5.15.2\android\mkspecs\features\spec_pre.prf \
		..\..\..\..\Qt\5.15.2\android\mkspecs\common\unix.conf \
		..\..\..\..\Qt\5.15.2\android\mkspecs\common\linux.conf \
		..\..\..\..\Qt\5.15.2\android\mkspecs\common\sanitize.conf \
		..\..\..\..\Qt\5.15.2\android\mkspecs\common\gcc-base.conf \
		..\..\..\..\Qt\5.15.2\android\mkspecs\common\gcc-base-unix.conf \
		..\..\..\..\Qt\5.15.2\android\mkspecs\common\clang.conf \
		..\..\..\..\Qt\5.15.2\android\mkspecs\qdevice.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\features\device_config.prf \
		..\..\..\..\Qt\5.15.2\android\mkspecs\qconfig.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_3danimation.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_3danimation_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_3dcore.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_3dcore_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_3dextras.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_3dextras_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_3dinput.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_3dinput_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_3dlogic.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_3dlogic_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_3dquick.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_3dquick_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_3dquickanimation.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_3dquickanimation_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_3dquickextras.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_3dquickextras_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_3dquickinput.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_3dquickinput_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_3dquickrender.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_3dquickrender_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_3dquickscene2d.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_3dquickscene2d_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_3drender.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_3drender_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_accessibility_support_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_androidextras.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_androidextras_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_bluetooth.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_bluetooth_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_bootstrap_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_charts.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_charts_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_concurrent.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_concurrent_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_core.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_core_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_datavisualization.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_datavisualization_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_devicediscovery_support_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_edid_support_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_egl_support_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_fb_support_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_fontdatabase_support_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_gamepad.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_gamepad_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_gui.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_gui_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_help.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_help_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_input_support_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_location.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_location_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_multimedia.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_multimedia_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_multimediawidgets.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_network.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_network_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_networkauth.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_networkauth_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_nfc.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_nfc_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_opengl.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_opengl_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_openglextensions.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_openglextensions_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_platformcompositor_support_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_positioning.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_positioning_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_positioningquick.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_positioningquick_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_printsupport.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_printsupport_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_qml.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_qml_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_qmldebug_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_qmlmodels.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_qmlmodels_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_qmltest.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_qmltest_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_qmlworkerscript.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_qmlworkerscript_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_quick.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_quick3d.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_quick3d_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_quick3dassetimport.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_quick3dassetimport_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_quick3drender.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_quick3drender_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_quick3druntimerender.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_quick3druntimerender_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_quick3dutils.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_quick3dutils_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_quick_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_quickcontrols2.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_quickparticles_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_quickshapes_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_quicktemplates2.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_quickwidgets.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_remoteobjects.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_remoteobjects_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_repparser.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_repparser_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_scxml.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_scxml_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_sensors.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_sensors_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_serialport.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_serialport_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_service_support_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_sql.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_sql_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_svg.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_svg_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_testlib.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_testlib_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_texttospeech.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_texttospeech_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_theme_support_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_uiplugin.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_uitools.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_uitools_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_vulkan_support_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_webchannel.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_webchannel_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_websockets.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_websockets_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_webview.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_webview_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_widgets.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_widgets_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_xml.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_xml_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_xmlpatterns.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_zlib_private.pri \
		..\..\..\..\Qt\5.15.2\android\mkspecs\features\qt_functions.prf \
		..\..\..\..\Qt\5.15.2\android\mkspecs\features\qt_config.prf \
		..\..\..\..\Qt\5.15.2\android\mkspecs\android-clang\qmake.conf \
		..\..\..\..\Qt\5.15.2\android\mkspecs\features\spec_post.prf \
		..\..\..\..\Qt\5.15.2\android\mkspecs\features\android\spec_post.prf \
		..\..\..\..\Qt\5.15.2\android\mkspecs\features\exclusive_builds.prf \
		..\..\..\..\Qt\5.15.2\android\mkspecs\features\toolchain.prf \
		..\..\..\..\Qt\5.15.2\android\mkspecs\features\default_pre.prf \
		..\..\..\..\Qt\5.15.2\android\mkspecs\features\android\default_pre.prf \
		..\..\..\..\Qt\5.15.2\android\mkspecs\features\resolve_config.prf \
		..\..\..\..\Qt\5.15.2\android\mkspecs\features\android\resolve_config.prf \
		..\..\..\..\Qt\5.15.2\android\mkspecs\features\exclusive_builds_post.prf \
		..\..\..\..\Qt\5.15.2\android\mkspecs\features\default_post.prf \
		..\..\..\..\Qt\5.15.2\android\mkspecs\features\qml_debug.prf \
		..\..\..\..\Qt\5.15.2\android\mkspecs\features\android\android.prf \
		..\..\..\..\Qt\5.15.2\android\mkspecs\features\resources_functions.prf \
		..\..\..\..\Qt\5.15.2\android\mkspecs\features\android\android_deployment_settings.prf \
		..\..\..\..\Qt\5.15.2\android\mkspecs\features\warn_on.prf \
		..\..\..\..\Qt\5.15.2\android\mkspecs\features\qt.prf \
		..\..\..\..\Qt\5.15.2\android\mkspecs\features\resources.prf \
		..\..\..\..\Qt\5.15.2\android\mkspecs\features\moc.prf \
		..\..\..\..\Qt\5.15.2\android\mkspecs\features\unix\opengl.prf \
		..\..\..\..\Qt\5.15.2\android\mkspecs\features\unix\thread.prf \
		..\..\..\..\Qt\5.15.2\android\mkspecs\features\qmake_use.prf \
		..\..\..\..\Qt\5.15.2\android\mkspecs\features\file_copies.prf \
		..\..\..\..\Qt\5.15.2\android\mkspecs\features\testcase_targets.prf \
		..\..\..\..\Qt\5.15.2\android\mkspecs\features\exceptions.prf \
		..\..\..\..\Qt\5.15.2\android\mkspecs\features\yacc.prf \
		..\..\..\..\Qt\5.15.2\android\mkspecs\features\lex.prf \
		Schegolkova_191_352_4sem.pro \
		..\..\..\..\Qt\5.15.2\android\lib\libQt5Quick_arm64-v8a.prl \
		..\..\..\..\Qt\5.15.2\android\lib\libQt5Gui_arm64-v8a.prl \
		..\..\..\..\Qt\5.15.2\android\lib\libQt5QmlModels_arm64-v8a.prl \
		..\..\..\..\Qt\5.15.2\android\lib\libQt5Qml_arm64-v8a.prl \
		..\..\..\..\Qt\5.15.2\android\lib\libQt5Network_arm64-v8a.prl \
		..\..\..\..\Qt\5.15.2\android\lib\libQt5Core_arm64-v8a.prl \
		.qmake.stash \
		..\..\..\..\Qt\5.15.2\android\mkspecs\features\build_pass.prf \
		qml.qrc \
		..\..\..\..\Qt\5.15.2\android\lib\libQt5Quick_armeabi-v7a.prl \
		..\..\..\..\Qt\5.15.2\android\lib\libQt5Gui_armeabi-v7a.prl \
		..\..\..\..\Qt\5.15.2\android\lib\libQt5QmlModels_armeabi-v7a.prl \
		..\..\..\..\Qt\5.15.2\android\lib\libQt5Qml_armeabi-v7a.prl \
		..\..\..\..\Qt\5.15.2\android\lib\libQt5Network_armeabi-v7a.prl \
		..\..\..\..\Qt\5.15.2\android\lib\libQt5Core_armeabi-v7a.prl \
		..\..\..\..\Qt\5.15.2\android\lib\libQt5Quick_x86.prl \
		..\..\..\..\Qt\5.15.2\android\lib\libQt5Gui_x86.prl \
		..\..\..\..\Qt\5.15.2\android\lib\libQt5QmlModels_x86.prl \
		..\..\..\..\Qt\5.15.2\android\lib\libQt5Qml_x86.prl \
		..\..\..\..\Qt\5.15.2\android\lib\libQt5Network_x86.prl \
		..\..\..\..\Qt\5.15.2\android\lib\libQt5Core_x86.prl \
		..\..\..\..\Qt\5.15.2\android\lib\libQt5Quick_x86_64.prl \
		..\..\..\..\Qt\5.15.2\android\lib\libQt5Gui_x86_64.prl \
		..\..\..\..\Qt\5.15.2\android\lib\libQt5QmlModels_x86_64.prl \
		..\..\..\..\Qt\5.15.2\android\lib\libQt5Qml_x86_64.prl \
		..\..\..\..\Qt\5.15.2\android\lib\libQt5Network_x86_64.prl \
		..\..\..\..\Qt\5.15.2\android\lib\libQt5Core_x86_64.prl
	$(QMAKE) -o Makefile Schegolkova_191_352_4sem.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug" "ANDROID_ABIS=armeabi-v7a x86 x86_64"
..\..\..\..\Qt\5.15.2\android\mkspecs\features\spec_pre.prf:
..\..\..\..\Qt\5.15.2\android\mkspecs\common\unix.conf:
..\..\..\..\Qt\5.15.2\android\mkspecs\common\linux.conf:
..\..\..\..\Qt\5.15.2\android\mkspecs\common\sanitize.conf:
..\..\..\..\Qt\5.15.2\android\mkspecs\common\gcc-base.conf:
..\..\..\..\Qt\5.15.2\android\mkspecs\common\gcc-base-unix.conf:
..\..\..\..\Qt\5.15.2\android\mkspecs\common\clang.conf:
..\..\..\..\Qt\5.15.2\android\mkspecs\qdevice.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\features\device_config.prf:
..\..\..\..\Qt\5.15.2\android\mkspecs\qconfig.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_3danimation.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_3danimation_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_3dcore.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_3dcore_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_3dextras.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_3dextras_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_3dinput.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_3dinput_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_3dlogic.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_3dlogic_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_3dquick.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_3dquick_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_3dquickanimation.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_3dquickanimation_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_3dquickextras.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_3dquickextras_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_3dquickinput.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_3dquickinput_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_3dquickrender.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_3dquickrender_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_3dquickscene2d.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_3dquickscene2d_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_3drender.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_3drender_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_accessibility_support_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_androidextras.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_androidextras_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_bluetooth.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_bluetooth_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_bootstrap_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_charts.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_charts_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_concurrent.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_concurrent_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_core.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_core_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_datavisualization.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_datavisualization_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_devicediscovery_support_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_edid_support_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_egl_support_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_fb_support_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_fontdatabase_support_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_gamepad.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_gamepad_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_gui.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_gui_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_help.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_help_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_input_support_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_location.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_location_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_multimedia.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_multimedia_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_multimediawidgets.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_network.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_network_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_networkauth.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_networkauth_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_nfc.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_nfc_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_opengl.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_opengl_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_openglextensions.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_openglextensions_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_packetprotocol_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_platformcompositor_support_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_positioning.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_positioning_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_positioningquick.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_positioningquick_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_printsupport.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_printsupport_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_qml.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_qml_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_qmldebug_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_qmldevtools_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_qmlmodels.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_qmlmodels_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_qmltest.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_qmltest_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_qmlworkerscript.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_qmlworkerscript_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_quick.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_quick3d.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_quick3d_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_quick3dassetimport.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_quick3dassetimport_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_quick3drender.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_quick3drender_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_quick3druntimerender.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_quick3druntimerender_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_quick3dutils.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_quick3dutils_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_quick_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_quickcontrols2.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_quickparticles_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_quickshapes_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_quicktemplates2.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_quickwidgets.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_quickwidgets_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_remoteobjects.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_remoteobjects_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_repparser.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_repparser_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_scxml.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_scxml_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_sensors.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_sensors_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_serialport.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_serialport_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_service_support_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_sql.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_sql_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_svg.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_svg_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_testlib.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_testlib_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_texttospeech.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_texttospeech_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_theme_support_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_uiplugin.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_uitools.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_uitools_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_vulkan_support_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_webchannel.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_webchannel_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_websockets.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_websockets_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_webview.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_webview_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_widgets.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_widgets_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_xml.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_xml_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_xmlpatterns.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\modules\qt_lib_zlib_private.pri:
..\..\..\..\Qt\5.15.2\android\mkspecs\features\qt_functions.prf:
..\..\..\..\Qt\5.15.2\android\mkspecs\features\qt_config.prf:
..\..\..\..\Qt\5.15.2\android\mkspecs\android-clang\qmake.conf:
..\..\..\..\Qt\5.15.2\android\mkspecs\features\spec_post.prf:
..\..\..\..\Qt\5.15.2\android\mkspecs\features\android\spec_post.prf:
..\..\..\..\Qt\5.15.2\android\mkspecs\features\exclusive_builds.prf:
..\..\..\..\Qt\5.15.2\android\mkspecs\features\toolchain.prf:
..\..\..\..\Qt\5.15.2\android\mkspecs\features\default_pre.prf:
..\..\..\..\Qt\5.15.2\android\mkspecs\features\android\default_pre.prf:
..\..\..\..\Qt\5.15.2\android\mkspecs\features\resolve_config.prf:
..\..\..\..\Qt\5.15.2\android\mkspecs\features\android\resolve_config.prf:
..\..\..\..\Qt\5.15.2\android\mkspecs\features\exclusive_builds_post.prf:
..\..\..\..\Qt\5.15.2\android\mkspecs\features\default_post.prf:
..\..\..\..\Qt\5.15.2\android\mkspecs\features\qml_debug.prf:
..\..\..\..\Qt\5.15.2\android\mkspecs\features\android\android.prf:
..\..\..\..\Qt\5.15.2\android\mkspecs\features\resources_functions.prf:
..\..\..\..\Qt\5.15.2\android\mkspecs\features\android\android_deployment_settings.prf:
..\..\..\..\Qt\5.15.2\android\mkspecs\features\warn_on.prf:
..\..\..\..\Qt\5.15.2\android\mkspecs\features\qt.prf:
..\..\..\..\Qt\5.15.2\android\mkspecs\features\resources.prf:
..\..\..\..\Qt\5.15.2\android\mkspecs\features\moc.prf:
..\..\..\..\Qt\5.15.2\android\mkspecs\features\unix\opengl.prf:
..\..\..\..\Qt\5.15.2\android\mkspecs\features\unix\thread.prf:
..\..\..\..\Qt\5.15.2\android\mkspecs\features\qmake_use.prf:
..\..\..\..\Qt\5.15.2\android\mkspecs\features\file_copies.prf:
..\..\..\..\Qt\5.15.2\android\mkspecs\features\testcase_targets.prf:
..\..\..\..\Qt\5.15.2\android\mkspecs\features\exceptions.prf:
..\..\..\..\Qt\5.15.2\android\mkspecs\features\yacc.prf:
..\..\..\..\Qt\5.15.2\android\mkspecs\features\lex.prf:
Schegolkova_191_352_4sem.pro:
..\..\..\..\Qt\5.15.2\android\lib\libQt5Quick_arm64-v8a.prl:
..\..\..\..\Qt\5.15.2\android\lib\libQt5Gui_arm64-v8a.prl:
..\..\..\..\Qt\5.15.2\android\lib\libQt5QmlModels_arm64-v8a.prl:
..\..\..\..\Qt\5.15.2\android\lib\libQt5Qml_arm64-v8a.prl:
..\..\..\..\Qt\5.15.2\android\lib\libQt5Network_arm64-v8a.prl:
..\..\..\..\Qt\5.15.2\android\lib\libQt5Core_arm64-v8a.prl:
.qmake.stash:
..\..\..\..\Qt\5.15.2\android\mkspecs\features\build_pass.prf:
qml.qrc:
..\..\..\..\Qt\5.15.2\android\lib\libQt5Quick_armeabi-v7a.prl:
..\..\..\..\Qt\5.15.2\android\lib\libQt5Gui_armeabi-v7a.prl:
..\..\..\..\Qt\5.15.2\android\lib\libQt5QmlModels_armeabi-v7a.prl:
..\..\..\..\Qt\5.15.2\android\lib\libQt5Qml_armeabi-v7a.prl:
..\..\..\..\Qt\5.15.2\android\lib\libQt5Network_armeabi-v7a.prl:
..\..\..\..\Qt\5.15.2\android\lib\libQt5Core_armeabi-v7a.prl:
..\..\..\..\Qt\5.15.2\android\lib\libQt5Quick_x86.prl:
..\..\..\..\Qt\5.15.2\android\lib\libQt5Gui_x86.prl:
..\..\..\..\Qt\5.15.2\android\lib\libQt5QmlModels_x86.prl:
..\..\..\..\Qt\5.15.2\android\lib\libQt5Qml_x86.prl:
..\..\..\..\Qt\5.15.2\android\lib\libQt5Network_x86.prl:
..\..\..\..\Qt\5.15.2\android\lib\libQt5Core_x86.prl:
..\..\..\..\Qt\5.15.2\android\lib\libQt5Quick_x86_64.prl:
..\..\..\..\Qt\5.15.2\android\lib\libQt5Gui_x86_64.prl:
..\..\..\..\Qt\5.15.2\android\lib\libQt5QmlModels_x86_64.prl:
..\..\..\..\Qt\5.15.2\android\lib\libQt5Qml_x86_64.prl:
..\..\..\..\Qt\5.15.2\android\lib\libQt5Network_x86_64.prl:
..\..\..\..\Qt\5.15.2\android\lib\libQt5Core_x86_64.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Schegolkova_191_352_4sem.pro -spec android-clang "CONFIG+=debug" "CONFIG+=qml_debug" "ANDROID_ABIS=armeabi-v7a x86 x86_64"

qmake_all: FORCE

make_first: armeabi-v7a-make_first x86-make_first x86_64-make_first  FORCE
all: armeabi-v7a-all x86-all x86_64-all  FORCE
clean: armeabi-v7a-clean x86-clean x86_64-clean android-build-distclean FORCE
distclean: armeabi-v7a-distclean x86-distclean x86_64-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash

android-build-distclean:
	rmdir /s /q C:\Users\Vasilisa\Documents\Schegolkova_191_352_4sem\android-build

aab: apk_install_target
	C:\Qt\5.15.2\android\bin\androiddeployqt.exe --input C:/Users/Vasilisa/Documents/Schegolkova_191_352_4sem/android-Schegolkova_191_352_4sem-deployment-settings.json --output C:/Users/Vasilisa/Documents/Schegolkova_191_352_4sem/android-build --aab --apk C:\Users\Vasilisa\Documents\Schegolkova_191_352_4sem\android-build\Schegolkova_191_352_4sem.apk

apk: apk_install_target
	C:\Qt\5.15.2\android\bin\androiddeployqt.exe --input C:/Users/Vasilisa/Documents/Schegolkova_191_352_4sem/android-Schegolkova_191_352_4sem-deployment-settings.json --output C:/Users/Vasilisa/Documents/Schegolkova_191_352_4sem/android-build --apk C:\Users\Vasilisa\Documents\Schegolkova_191_352_4sem\android-build\Schegolkova_191_352_4sem.apk

apk_install_target: first
	$(MAKE) -f $(MAKEFILE) INSTALL_ROOT=C:\Users\Vasilisa\Documents\Schegolkova_191_352_4sem\android-build install

armeabi-v7a-mocclean:
	$(MAKE) -f $(MAKEFILE).Armeabi-v7a mocclean
x86-mocclean:
	$(MAKE) -f $(MAKEFILE).X86 mocclean
x86_64-mocclean:
	$(MAKE) -f $(MAKEFILE).X86_64 mocclean
mocclean: armeabi-v7a-mocclean x86-mocclean x86_64-mocclean

armeabi-v7a-mocables:
	$(MAKE) -f $(MAKEFILE).Armeabi-v7a mocables
x86-mocables:
	$(MAKE) -f $(MAKEFILE).X86 mocables
x86_64-mocables:
	$(MAKE) -f $(MAKEFILE).X86_64 mocables
mocables: armeabi-v7a-mocables x86-mocables x86_64-mocables

check: first

benchmark: first
FORCE:

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: armeabi-v7a-distdir x86-distdir x86_64-distdir FORCE
	@if not exist $(DISTDIR) mkdir $(DISTDIR) & if not exist $(DISTDIR) exit 1
	$(COPY_FILE) --parents  $(DISTDIR)\

armeabi-v7a-distdir: FORCE
	$(MAKE) -e -f $(MAKEFILE).Armeabi-v7a distdir DISTDIR=$(DISTDIR)\

x86-distdir: FORCE
	$(MAKE) -e -f $(MAKEFILE).X86 distdir DISTDIR=$(DISTDIR)\

x86_64-distdir: FORCE
	$(MAKE) -e -f $(MAKEFILE).X86_64 distdir DISTDIR=$(DISTDIR)\

$(MAKEFILE).Armeabi-v7a: Makefile
$(MAKEFILE).X86: Makefile
$(MAKEFILE).X86_64: Makefile
